# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudentprofessor',
            name='feedback_status',
        ),
    ]
