# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_coursestudentprofessor_feedback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='message',
        ),
        migrations.RemoveField(
            model_name='course',
            name='starting_date',
        ),
    ]
