# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170328_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='end_date',
            field=models.DateField(default=datetime.date(2017, 4, 8)),
        ),
        migrations.AlterField(
            model_name='requestfeedback',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 3, 29)),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together=set([('course', 'student')]),
        ),
    ]
