# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20170124_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursestudentprofessor',
            name='courseprofessor',
        ),
        migrations.RemoveField(
            model_name='coursestudentprofessor',
            name='coursestudent',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='courseprofessor',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='feedback_status',
        ),
        migrations.DeleteModel(
            name='CourseStudentProfessor',
        ),
        migrations.AddField(
            model_name='feedback',
            name='fid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.RequestFeedback'),
        ),
    ]
