# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170329_0830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprofessor',
            unique_together=set([('course', 'professor')]),
        ),
    ]
