# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170126_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RequestFeedback'),
        ),
    ]
