# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170126_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSVFile', models.FileField(upload_to=b'')),
            ],
        ),
    ]
