# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Feedback Portal Admins'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseprofessor',
            options={'verbose_name_plural': 'Course Professors'},
        ),
        migrations.AlterModelOptions(
            name='coursestudent',
            options={'verbose_name_plural': 'Course Students'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback Responses'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='requestfeedback',
            options={'verbose_name_plural': 'Feedback Requisition Table'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='CSVFile',
            field=models.FileField(upload_to=''),
        ),
    ]
