# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170210_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='fullname',
            field=models.CharField(default='FULLNAME', max_length=100),
        ),
    ]
