# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='end_date',
            field=models.DateField(default=datetime.date(2017, 3, 5)),
        ),
        migrations.AlterField(
            model_name='requestfeedback',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 2, 23)),
        ),
    ]
