# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170223_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='end_date',
            field=models.DateField(default=datetime.date(2017, 3, 18)),
        ),
        migrations.AlterField(
            model_name='requestfeedback',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 3, 8)),
        ),
    ]
